version: '3.8'
services:
    database:
        container_name: nest-database
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_NAME
        ports:
            - $DB_PORT:5432
        env_file:
            - .env
        volumes:
            - .docker/db:/var/lib/postgresql
        networks:
            - nest-network

networks:
    nest-network: